# Generated by Django 5.1.5 on 2026-03-29 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'created_at'], name='accounts_us_user_id_ab8ad3_idx'),
        ),
    ]
