# Generated by Django 5.1.5 on 2026-05-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profilecredentialdocument_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilecredentialdocument',
            options={'ordering': ['display_order', 'id']},
        ),
    ]
