# Generated by Django 5.1.5 on 2026-05-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profilecredentialdocument_options'),
        ('accounts', '0005_profileupdatereviewitem'),
    ]

    operations = [
    ]
