# Generated by Django 5.1.5 on 2026-05-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260507_0930'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profileupdatereviewitem',
            new_name='accounts_pr_status_26777a_idx',
            old_name='accounts_pr_status_1d68ce_idx',
        ),
    ]
