# Generated by Django 5.1.5 on 2026-03-05 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('lunch_out', models.DateTimeField(blank=True, null=True)),
                ('lunch_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('missing_punch_flagged', models.BooleanField(default=False, help_text='Set by nightly job when entry is incomplete; cleared when entry is fixed.')),
                ('missing_punch_flagged_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='timeclock_t_user_id_026cd9_idx'), models.Index(fields=['date'], name='timeclock_t_date_451fab_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_timeentry_user_date')],
            },
        ),
    ]
