# Generated by Django 5.1.5 on 2026-03-29 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0003_timeentry_clock_in_authorized_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='clock_in_authorized_by',
            field=models.ForeignKey(blank=True, help_text='Manager/supervisor who approved clock-in when unscheduled or more than 15 minutes early.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_clock_ins', to=settings.AUTH_USER_MODEL),
        ),
    ]
