# Generated by Django 5.1.5 on 2026-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0007_timeentry_payroll_lunch_review_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='payroll_lunch_review_required',
            field=models.BooleanField(default=False, help_text='Payroll CSV omitted lunch on a scheduled-lunch day; confirm scheduled lunch or work-through at finalize before closing payroll.'),
        ),
    ]
