# Generated by Django 5.1.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeclock", "0008_alter_timeentry_payroll_lunch_review_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeclockKioskIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="Static IPv4 address of the kiosk machine (e.g. 192.168.1.50).",
                        protocol="IPv4",
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Optional name, e.g. "Break room" or "Plant floor".',
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive kiosks use the normal login + PIN timeclock.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Timeclock kiosk IP",
                "verbose_name_plural": "Timeclock kiosk IPs",
                "ordering": ["ip_address"],
            },
        ),
    ]
