# Generated by Django 5.1.5

from django.db import migrations, models
import timeclock.models


class Migration(migrations.Migration):

    dependencies = [
        ("timeclock", "0009_timeclockkioskip"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeclockKioskToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=timeclock.models._generate_kiosk_token,
                        editable=False,
                        help_text="Secret value for ?kiosk= on the timeclock URL.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Optional name, e.g. "Work plant Pi".',
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive tokens no longer enable kiosk mode.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Timeclock kiosk token",
                "verbose_name_plural": "Timeclock kiosk tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
