"""
Django settings for tfapp project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Set DJANGO_SECRET_KEY in production. The fallback is dev-only.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-c&a_*#xv07(2=f2f554*&-)#895yfjq2an)aoo$ejag58mvzi7",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,tfapp.freedomwoods.online,127.0.0.1",
    ).split(",")
    if h.strip()
]

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "https://tfapp.freedomwoods.online",
    ).split(",")
    if o.strip()
]

# --- HTTPS / browser security (defaults: strict when DEBUG is False) ---
def _env_bool(name: str, default: bool) -> bool:
    v = os.environ.get(name)
    if v is None:
        return default
    return v.lower() in ("1", "true", "yes")


SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

# If behind a reverse proxy that terminates TLS, set DJANGO_SECURE_PROXY_SSL_HEADER=1
if os.environ.get("DJANGO_SECURE_PROXY_SSL_HEADER", "").lower() in ("1", "true", "yes"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# --- Sessions: 1.5 hours of inactivity (sliding expiry on each request) ---
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = int(os.environ.get("SESSION_COOKIE_AGE", str(90 * 60)))
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
# False = fewer session DB writes (better under SQLite + concurrent requests). True = sliding expiry on every request.
SESSION_SAVE_EVERY_REQUEST = _env_bool("DJANGO_SESSION_SAVE_EVERY_REQUEST", False)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "tfapp",
    }
}

# Dashboard absenteeism chart JSON is cached to avoid recomputing ~3 years of schedule math.
# Default 1 hour. For multiple Gunicorn workers, LocMem is per-process—set CACHES to Redis
# (see Django docs) so all workers share one cache, or raise this TTL.
ABSENTEEISM_CHART_CACHE_SECONDS = int(
    os.environ.get("DJANGO_ABSENTEEISM_CHART_CACHE_SECONDS", str(60 * 60))
)

# Perfect Attendance table on dashboard (expensive); cache serialized rows per month/period.
PERFECT_ATTENDANCE_CACHE_SECONDS = int(
    os.environ.get("DJANGO_PERFECT_ATTENDANCE_CACHE_SECONDS", str(10 * 60))
)

# Dashboard + payroll weekly summary row (same computation); short TTL keeps punches fresh.
WEEKLY_TOTALS_CACHE_SECONDS = int(os.environ.get("DJANGO_WEEKLY_TOTALS_CACHE_SECONDS", "90"))

# Absenteeism chart: how many completed calendar years to show as bars (1–3). Lower = faster.
ABSENTEEISM_CHART_YEAR_BARS = int(os.environ.get("DJANGO_ABSENTEEISM_CHART_YEAR_BARS", "1"))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'pages.apps.PagesConfig',
    'attendance',
    'timeclock',
    'resources.apps.ResourcesConfig',
    'crispy_forms',
    'crispy_bootstrap5',
]

CRISPY_TEMPLATE_PACK = 'bootstrap5'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.UserSessionTrackingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tfapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'attendance.context_processors.pending_approvals',
            ],
        },
    },
]

WSGI_APPLICATION = 'tfapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            # Longer busy timeout reduces "database is locked" under concurrent reads/writes (e.g. chart + dashboard).
            "timeout": int(os.environ.get("DJANGO_SQLITE_TIMEOUT", "30")),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'attendance.CustomUser'
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Detroit'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Directory for `collectstatic` to gather all static files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional directories to look for static files during development
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Add your app-specific static directory
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Auth redirects (paths match accounts/urls.py, no trailing slash) ---
LOGIN_URL = "/accounts/login"
LOGIN_REDIRECT_URL = "/"

# --- Email (password reset & notifications) ---
#
# Default: console backend prints messages to the runserver terminal only (no real email).
#
# To send real mail (e.g. Gmail for testing): set env vars below. If EMAIL_HOST is set,
# SMTP is used automatically; you do not need to set EMAIL_BACKEND.
#
# Gmail (personal account for testing):
#   1. Enable 2-Step Verification on the Google account.
#   2. Create an App Password: https://myaccount.google.com/apppasswords
#      (Google Account > Security > 2-Step Verification > App passwords)
#   3. Export before starting Django, e.g. in your shell or a .env loader:
#        export EMAIL_HOST=smtp.gmail.com
#        export EMAIL_PORT=587
#        export EMAIL_USE_TLS=1
#        export EMAIL_HOST_USER=you@gmail.com
#        export EMAIL_HOST_PASSWORD=xxxx xxxx xxxx xxxx   # 16-char app password, spaces optional
#        export DEFAULT_FROM_EMAIL="You <you@gmail.com>"
#        export SERVER_EMAIL=you@gmail.com
#   Use the same address for DEFAULT_FROM_EMAIL as EMAIL_HOST_USER unless you have
#   "Send mail as" configured in Gmail.
#
# Optional: set DJANGO_SITE_BASE_URL (or SITE_BASE_URL) for management commands that need
# an absolute site URL (e.g. some email utilities). Approval notifications use in-app navigation
# text instead of hyperlinks.
#
if os.environ.get("EMAIL_HOST"):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
elif "EMAIL_BACKEND" in os.environ:
    EMAIL_BACKEND = os.environ["EMAIL_BACKEND"]
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "webmaster@localhost")
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

# Optional absolute site URL (no trailing slash), e.g. for management commands / legacy tools
SITE_BASE_URL = os.environ.get("DJANGO_SITE_BASE_URL", os.environ.get("SITE_BASE_URL", "")).strip().rstrip("/")
BASE_URL = SITE_BASE_URL

if EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend":
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "30"))
