# Generated by Django 5.1.5 on 2026-03-05 21:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('executive', 'Executive'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('group_lead', 'Group Lead'), ('team_lead', 'Team Lead'), ('user', 'User')], default='user', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_part_time', models.BooleanField(default=False)),
                ('is_exempt', models.BooleanField(default=False)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('pto_balance', models.FloatField(default=0.0)),
                ('personal_time_balance', models.FloatField(default=0.0)),
                ('final_pto_balance', models.FloatField(default=0.0)),
                ('hours_worked', models.FloatField(default=0.0)),
                ('timeclock_login', models.CharField(blank=True, max_length=4, null=True)),
                ('timeclock_pin', models.CharField(blank=True, max_length=4, null=True)),
                ('weekly_schedule', models.JSONField(blank=True, default=dict, null=True)),
                ('group_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_members', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisees', to=settings.AUTH_USER_MODEL)),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateField(unique=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_ending'],
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('planned', models.BooleanField(default=False)),
                ('subtype', models.CharField(choices=[('Time Off', 'Time Off'), ('Tardy In Grace', 'Tardy In Grace'), ('Tardy Out of Grace', 'Tardy Out of Grace'), ('Exchange', 'Exchange'), ('FMLA', 'Family Medical Leave'), ('LOA', 'Leave of Absence'), ('Transportation', 'Transportation'), ('Weather Unpaid', 'Inclement Weather - Unpaid'), ('Weather Paid', 'Inclement Weather - Paid'), ('Bereavement Paid', 'Bereavement - Paid'), ('Bereavement Unpaid', 'Bereavement - Unpaid'), ('Jury Duty Paid', 'Jury Duty - Paid'), ('Jury Duty Unpaid', 'Jury Duty - Unpaid'), ('Discipline', 'Discipline'), ('Work Comp', 'Work Comp'), ('Disability', 'Disability'), ('Holiday Paid', 'Holiday - Paid')], default='Time Off', max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_off_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriodUserSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pto_accrued_hours', models.FloatField(default=0.0)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_snapshots', to='attendance.payrollperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_period_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period', 'user'],
                'unique_together': {('period', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PTOBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.DecimalField(decimal_places=2, help_text='Signed change amount', max_digits=8)),
                ('reason', models.CharField(max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Balance after this change', max_digits=8)),
                ('balance_type', models.CharField(choices=[('pto', 'PTO'), ('personal', 'Personal')], default='pto', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_balance_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='attendance__user_id_32e97e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_type', models.CharField(choices=[('Planned', 'Planned'), ('Unplanned', 'Unplanned')], max_length=20)),
                ('subtype', models.CharField(choices=[('Time Off', 'Time Off'), ('Tardy In Grace', 'Tardy In Grace'), ('Tardy Out of Grace', 'Tardy Out of Grace'), ('Exchange', 'Exchange'), ('FMLA', 'Family Medical Leave'), ('LOA', 'Leave of Absence'), ('Transportation', 'Transportation'), ('Weather Unpaid', 'Inclement Weather - Unpaid'), ('Weather Paid', 'Inclement Weather - Paid'), ('Bereavement Paid', 'Bereavement - Paid'), ('Bereavement Unpaid', 'Bereavement - Unpaid'), ('Jury Duty Paid', 'Jury Duty - Paid'), ('Jury Duty Unpaid', 'Jury Duty - Unpaid'), ('Discipline', 'Discipline'), ('Work Comp', 'Work Comp'), ('Disability', 'Disability'), ('Holiday Paid', 'Holiday - Paid')], max_length=50)),
                ('date', models.DateField()),
                ('duration_hours', models.FloatField(default=0.0)),
                ('pto_applied', models.BooleanField(default=False)),
                ('pto_hours_applied', models.FloatField(default=0.0)),
                ('personal_hours_applied', models.FloatField(default=0.0)),
                ('is_variance_to_schedule', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(blank=True, help_text='Set when this occurrence was created at payroll finalize (variance or tardy); used to revert on unfinalize.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences_created', to='attendance.payrollperiod')),
                ('time_off_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='attendance.timeoffrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='attendance__user_id_45b779_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('subtype', 'Tardy In Grace')), fields=('user', 'date', 'subtype'), name='unique_tardy_in_grace_per_user_date'), models.UniqueConstraint(condition=models.Q(('subtype', 'Tardy Out of Grace')), fields=('user', 'date', 'subtype'), name='unique_tardy_out_of_grace_per_user_date')],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('lunch_out', models.TimeField()),
                ('lunch_in', models.TimeField()),
                ('end_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('user', 'day')},
            },
        ),
    ]
