# Generated by Django 5.1.5 on 2026-03-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_occurrence_subtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payroll_firstname',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payroll_lastname',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
