# Generated by Django 5.1.5 on 2026-03-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_customuser_payroll_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='partial_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='partial_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
