# Generated by Django 5.1.5 on 2026-02-27 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_customuser_weekly_schedule_workschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='subtype',
            field=models.CharField(choices=[('Time Off', 'Time Off'), ('Tardy In Grace', 'Tardy In Grace'), ('Tardy Out of Grace', 'Tardy Out of Grace'), ('Exchange', 'Exchange'), ('FMLA', 'Family Medical Leave'), ('LOA', 'Leave of Absence'), ('Transportation', 'Transportation'), ('Weather Unpaid', 'Inclement Weather - Unpaid'), ('Weather Paid', 'Inclement Weather - Paid'), ('Bereavement Paid', 'Bereavement - Paid'), ('Bereavement Unpaid', 'Bereavement - Unpaid'), ('Jury Duty Paid', 'Jury Duty - Paid'), ('Jury Duty Unpaid', 'Jury Duty - Unpaid'), ('Discipline', 'Discipline'), ('Work Comp', 'Work Comp'), ('Disability', 'Disability'), ('Holiday Paid', 'Holiday - Paid')], max_length=50),
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('planned', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_off_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
