# Generated by Django 5.1.5 on 2026-04-05 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_delete_payrollperiodscheduleoverride'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'verbose_name': 'Absence', 'verbose_name_plural': 'Absences'},
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='occurrence_type',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Unplanned', 'Unplanned')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='payroll_period',
            field=models.ForeignKey(blank=True, help_text='Set when this absence was created at payroll finalize (variance or tardy); used to revert on unfinalize.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences_created', to='attendance.payrollperiod'),
        ),
    ]
