# Generated by Django 5.1.5 on 2026-04-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_occurrence_options_and_more'),
        ('attendance', '0014_alter_occurrence_options_and_more'),
    ]

    operations = [
    ]
