# Generated by Django 5.1.5 on 2026-05-08 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_occurrence_probation_grace_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('scheduled_hours', models.FloatField(default=0.0)),
                ('worked_hours', models.FloatField(default=0.0)),
                ('rounded_hours', models.FloatField(default=0.0)),
                ('lunch_deducted_hours', models.FloatField(default=0.0)),
                ('tardy_minutes', models.IntegerField(default=0)),
                ('early_out_minutes', models.IntegerField(default=0)),
                ('regular_hours', models.FloatField(default=0.0)),
                ('overtime_hours', models.FloatField(default=0.0)),
                ('exchange_eligible', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('provisional', 'Provisional'), ('approved', 'Approved'), ('finalized', 'Finalized')], default='open', max_length=20)),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendance_summaries', to='attendance.payrollperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['work_date', 'user_id'],
                'indexes': [models.Index(fields=['user', 'work_date'], name='attendance__user_id_8530a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'work_date'), name='unique_daily_attendance_summary_user_work_date')],
            },
        ),
    ]
