# Generated by Django 5.1.5 on 2026-04-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_merge_20260405_1130'),
        ('attendance', '0015_occurrence_probation_grace_hours'),
    ]

    operations = [
    ]
