# Generated by Django 5.1.5 on 2026-04-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_merge_20260410_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='subtype',
            field=models.CharField(choices=[('Time Off', 'Time Off'), ('Tardy In Grace', 'Tardy In Grace'), ('Tardy Out of Grace', 'Tardy Out of Grace'), ('Exchange', 'Exchange'), ('Lay-Off', 'Lay-Off'), ('FMLA', 'Family Medical Leave'), ('LOA', 'Leave of Absence'), ('Weather Unpaid', 'Inclement Weather - Unpaid'), ('Weather Paid', 'Inclement Weather - Paid'), ('Bereavement Paid', 'Bereavement - Paid'), ('Bereavement Unpaid', 'Bereavement - Unpaid'), ('Jury Duty Paid', 'Jury Duty - Paid'), ('Jury Duty Unpaid', 'Jury Duty - Unpaid'), ('Discipline', 'Discipline'), ('Work Comp', 'Work Comp'), ('Disability', 'Disability'), ('Holiday Paid', 'Holiday - Paid'), ('Grace Time', 'Grace Time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='subtype',
            field=models.CharField(choices=[('Time Off', 'Time Off'), ('Tardy In Grace', 'Tardy In Grace'), ('Tardy Out of Grace', 'Tardy Out of Grace'), ('Exchange', 'Exchange'), ('Lay-Off', 'Lay-Off'), ('FMLA', 'Family Medical Leave'), ('LOA', 'Leave of Absence'), ('Weather Unpaid', 'Inclement Weather - Unpaid'), ('Weather Paid', 'Inclement Weather - Paid'), ('Bereavement Paid', 'Bereavement - Paid'), ('Bereavement Unpaid', 'Bereavement - Unpaid'), ('Jury Duty Paid', 'Jury Duty - Paid'), ('Jury Duty Unpaid', 'Jury Duty - Unpaid'), ('Discipline', 'Discipline'), ('Work Comp', 'Work Comp'), ('Disability', 'Disability'), ('Holiday Paid', 'Holiday - Paid'), ('Grace Time', 'Grace Time')], default='Time Off', max_length=50),
        ),
    ]
