# Generated by Django 5.1.5 on 2026-05-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_daily_attendance_summary_and_services'),
        ('attendance', '0017_alter_occurrence_subtype_and_more'),
    ]

    operations = [
    ]
