# Generated by Django 5.1.5 on 2025-04-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_occurrence_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timeclock_login',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timeclock_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
